
PAIRS = [
    {"base": "SPY",  "alt": "SPXL", "target_ratio": 3.0,  "emisor": "Direxion",  "nota": "S&P 500 bull 3x"},
    {"base": "SPY",  "alt": "SPXS", "target_ratio": -3.0, "emisor": "Direxion",  "nota": "S&P 500 bear 3x"},
    {"base": "QQQ",  "alt": "TQQQ", "target_ratio": 3.0,  "emisor": "ProShares", "nota": "Nasdaq-100 bull 3x"},
    {"base": "QQQ",  "alt": "SQQQ", "target_ratio": -3.0, "emisor": "ProShares", "nota": "Nasdaq-100 bear 3x"},
    {"base": "IWM",  "alt": "TNA",  "target_ratio": 3.0,  "emisor": "Direxion",  "nota": "Russell 2000 bull 3x"},
    {"base": "IWM",  "alt": "TZA",  "target_ratio": -3.0, "emisor": "Direxion",  "nota": "Russell 2000 bear 3x"},
    {"base": "DIA",  "alt": "UDOW", "target_ratio": 3.0,  "emisor": "ProShares", "nota": "Dow Jones 30 bull 3x"},
    {"base": "DIA",  "alt": "SDOW", "target_ratio": -3.0, "emisor": "ProShares", "nota": "Dow Jones 30 bear 3x"},
    {"base": "NVDA", "alt": "NVDL", "target_ratio": 1.5,  "emisor": "Direxion",  "nota": "Nvidia bull 1.5x"},
    {"base": "NVDA", "alt": "NVDX", "target_ratio": 2.0,  "emisor": "AXS/Tuttle","nota": "Nvidia bull 2x"},
    {"base": "TSLA", "alt": "TSLL", "target_ratio": 1.5,  "emisor": "Direxion",  "nota": "Tesla bull 1.5x"},
    {"base": "TSLA", "alt": "TSLT", "target_ratio": -1.5, "emisor": "Direxion",  "nota": "Tesla bear -1.5x"},
    {"base": "COIN", "alt": "CONL", "target_ratio": 1.5,  "emisor": "Direxion",  "nota": "Coinbase bull 1.5x"},
    {"base": "COIN", "alt": "CONY", "target_ratio": -1.5, "emisor": "Direxion",  "nota": "Coinbase bear -1.5x"},
    {"base": "MSTR", "alt": "MSTX", "target_ratio": 1.5,  "emisor": "Direxion",  "nota": "MicroStrategy bull 1.5x"},
    {"base": "AMZN", "alt": "AMZU", "target_ratio": 1.5,  "emisor": "Direxion",  "nota": "Amazon bull 1.5x"},
    {"base": "AMZN", "alt": "AMZD", "target_ratio": -1.5, "emisor": "Direxion",  "nota": "Amazon bear -1.5x"},
    {"base": "META", "alt": "METU", "target_ratio": 1.5,  "emisor": "Direxion",  "nota": "Meta bull 1.5x"},
    {"base": "META", "alt": "METD", "target_ratio": -1.5, "emisor": "Direxion",  "nota": "Meta bear -1.5x"},
    {"base": "MSFT", "alt": "MSFU", "target_ratio": 1.5,  "emisor": "Direxion",  "nota": "Microsoft bull 1.5x"},
    {"base": "MSFT", "alt": "MSFD", "target_ratio": -1.5, "emisor": "Direxion",  "nota": "Microsoft bear -1.5x"},
    {"base": "GOOG", "alt": "GGLL", "target_ratio": 1.5,  "emisor": "Direxion",  "nota": "Google bull 1.5x"},
    {"base": "GOOG", "alt": "GGLS", "target_ratio": -1.5, "emisor": "Direxion",  "nota": "Google bear -1.5x"},
    {"base": "AAPL", "alt": "AAPU", "target_ratio": 1.5,  "emisor": "Direxion",  "nota": "Apple bull 1.5x"},
    {"base": "AAPL", "alt": "AAPD", "target_ratio": -1.5, "emisor": "Direxion",  "nota": "Apple bear -1.5x"},
    {"base": "SOXX", "alt": "SOXL", "target_ratio": 3.0,  "emisor": "Direxion",  "nota": "Semiconductores bull 3x"},
    {"base": "SOXX", "alt": "SOXS", "target_ratio": -3.0, "emisor": "Direxion",  "nota": "Semiconductores bear 3x"},
    {"base": "XLF",  "alt": "FAS",  "target_ratio": 3.0,  "emisor": "Direxion",  "nota": "Financiero bull 3x"},
    {"base": "XLF",  "alt": "FAZ",  "target_ratio": -3.0, "emisor": "Direxion",  "nota": "Financiero bear 3x"},
    {"base": "XLE",  "alt": "ERX",  "target_ratio": 3.0,  "emisor": "Direxion",  "nota": "Energía bull 3x"},
    {"base": "XLE",  "alt": "ERY",  "target_ratio": -3.0, "emisor": "Direxion",  "nota": "Energía bear 3x"},
    {"base": "GLD",  "alt": "UGL",  "target_ratio": 2.0,  "emisor": "ProShares", "nota": "Oro bull 2x"},
    {"base": "GLD",  "alt": "GLL",  "target_ratio": -2.0, "emisor": "ProShares", "nota": "Oro bear 2x"},
    {"base": "SLV",  "alt": "AGQ",  "target_ratio": 2.0,  "emisor": "ProShares", "nota": "Plata bull 2x"},
    {"base": "SLV",  "alt": "ZSL",  "target_ratio": -2.0, "emisor": "ProShares", "nota": "Plata bear 2x"},
    {"base": "USO",  "alt": "UCO",  "target_ratio": 2.0,  "emisor": "ProShares", "nota": "Petróleo bull 2x"},
    {"base": "USO",  "alt": "SCO",  "target_ratio": -2.0, "emisor": "ProShares", "nota": "Petróleo bear 2x"},
    {"base": "BITO","alt": "BITX", "target_ratio": 2.0,  "emisor": "Volatility Shares", "nota": "Bitcoin futures bull 2x"}
]
